# Generated by Django 3.1 on 2020-09-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upkoron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviece_name', models.TextField()),
                ('serviece_receiver', models.TextField()),
                ('current_serviece_delivery_method', models.TextField()),
                ('current_serviece_delivery_problems', models.TextField()),
                ('innovative_idea_title', models.TextField()),
                ('solution_process', models.TextField()),
                ('solution_process_map', models.TextField()),
                ('nobelness_in_idea', models.TextField()),
                ('equipments', models.TextField()),
                ('background_works_required', models.TextField()),
                ('tcv', models.TextField()),
                ('others_advantage', models.TextField()),
                ('resource_map', models.TextField()),
                ('implementation_team', models.TextField()),
                ('targeted_people_to_receive_advantage', models.TextField()),
                ('pilotting_activities', models.TextField()),
                ('risk_feared', models.TextField()),
                ('details_of_the_owner', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(max_length=250, null=True)),
                ('branch_code', models.IntegerField(null=True)),
                ('region', models.CharField(max_length=250, null=True)),
                ('division', models.CharField(max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
