# Generated by Django 3.1 on 2020-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upkoron',
            name='affected_people',
            field=models.TextField(default='sdf'),
            preserve_default=False,
        ),
    ]
