# Generated by Django 3.0.7 on 2020-07-08 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(max_length=250, null=True)),
                ('branch_code', models.IntegerField(null=True)),
                ('region', models.CharField(max_length=250, null=True)),
                ('division', models.CharField(max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_period_start', models.DateField()),
                ('audit_period_end', models.DateField(blank=True, null=True)),
                ('para_no', models.CharField(default=0, max_length=5)),
                ('para_type', models.CharField(choices=[('সাধারন', 'সাধারন'), ('অগ্রিম', 'অগ্রিম'), ('খসড়া', 'খসড়া'), ('সংকলন', 'সংকলন')], default='সাধারন', max_length=100)),
                ('present_objection_status', models.CharField(choices=[('নিষ্পন্ন', 'নিষ্পন্ন'), ('অনিষ্পন্ন', 'অনিষ্পন্ন')], default='অনিষ্পন্ন', max_length=100)),
                ('audit_Objection_Title', models.CharField(max_length=100)),
                ('amount', models.CharField(default=0, max_length=10)),
                ('cause_of_objection', models.CharField(choices=[('ভাউচার নাই', 'ভাউচার নাই'), ('আর্থিক বিধি অনুসরণ করা হয় নাই', 'আর্থিক বিধি অনুসরণ করা হয় নাই'), ('তামাদি ঋণ', 'তামাদি ঋণ'), ('আয়কর', 'আয়কর'), ('বিভিন্ন প্রকার অনাদায়ী ঋণ', 'বিভিন্ন প্রকার অনাদায়ী ঋণ'), ('গৃহ নির্মাণ অগ্রীম(জমি ক্রয়)', 'গৃহ নির্মাণ অগ্রীম(জমি ক্রয়)'), ('লাঞ্চ সাবসিডি', 'লাঞ্চ সাবসিডি'), ('অতিরিক্ত সুদ প্রদান', 'অতিরিক্ত সুদ প্রদান'), ('উৎস কর কম কর্তন', 'উৎস কর কম কর্তন'), ('ইত্যাদি', 'ইত্যাদি')], default='আর্থিক বিধি অনুসরণ করা হয় নাই', max_length=100)),
                ('recommendation', models.CharField(max_length=250)),
                ('action', models.CharField(max_length=250)),
                ('issued_letter_no', models.CharField(default=0, max_length=5)),
                ('issued_letter_date', models.DateField(blank=True, null=True)),
                ('last_reply_no', models.CharField(max_length=5)),
                ('last_reply_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
