# Generated by Django 3.0.7 on 2020-08-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_management', '0002_auto_20200709_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='finished_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='finished_letter_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cause_of_objection',
            field=models.TextField(choices=[('ভাউচার নাই', 'ভাউচার নাই'), ('আর্থিক বিধি অনুসরণ করা হয় নাই', 'আর্থিক বিধি অনুসরণ করা হয় নাই'), ('তামাদি ঋণ', 'তামাদি ঋণ'), ('আয়কর', 'আয়কর'), ('বিভিন্ন প্রকার অনাদায়ী ঋণ', 'বিভিন্ন প্রকার অনাদায়ী ঋণ'), ('গৃহ নির্মাণ অগ্রীম(জমি ক্রয়)', 'গৃহ নির্মাণ অগ্রীম(জমি ক্রয়)'), ('লাঞ্চ সাবসিডি', 'লাঞ্চ সাবসিডি'), ('অতিরিক্ত সুদ প্রদান', 'অতিরিক্ত সুদ প্রদান'), ('উৎস কর কম কর্তন', 'উৎস কর কম কর্তন'), ('বিবিধ', 'বিবিধ')], default='আর্থিক বিধি অনুসরণ করা হয় নাই', max_length=100),
        ),
    ]
