# Generated by Django 3.0.7 on 2020-08-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_management', '0003_auto_20200822_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_description', models.CharField(blank=True, max_length=200, null=True)),
                ('document', models.FileField(upload_to='media/%Y/%m/%d')),
                ('is_first', models.BooleanField(default=False)),
                ('expense_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_management.Expense')),
            ],
        ),
    ]
