# Generated by Django 3.1 on 2020-09-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_management', '0004_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='audit_year',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='fiscal_year',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='audit_Objection_Title',
            field=models.TextField(blank=True),
        ),
    ]
