# Generated by Django 3.0.7 on 2020-10-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_management', '0006_auto_20200913_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='suit_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='suit_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='suit_type',
            field=models.CharField(choices=[('সার্টিফিকেট', 'সার্টিফিকেট'), ('অর্থ ঋণ', 'অর্থ ঋণ'), ('ফৌজদারী', 'ফৌজদারী'), ('মানিস্যুট', 'মানিস্যুট'), ('অন্যান্য', 'অন্যান্য')], default='সার্টিফিকেট', max_length=100),
        ),
    ]
