# Generated by Django 3.1 on 2020-10-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_management', '0007_auto_20201019_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='have_suit',
            field=models.CharField(choices=[('হ্যাঁ', 'হ্যাঁ'), ('না', 'না')], default='না', max_length=100),
        ),
    ]
