# Generated by Django 3.1 on 2020-11-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_management', '0008_expense_have_suit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='suit_amount',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cause_of_objection',
            field=models.TextField(choices=[('ভাউচার নেই', 'ভাউচার নেই'), ('আর্থিক বিধি অনুসরণ করা হয় নাই', 'আর্থিক বিধি অনুসরণ করা হয় নাই'), ('আয়কর', 'আয়কর'), ('উৎস কর কম কর্তন', 'উৎস কর কম কর্তন'), ('ভ্যাট সংক্রান্ত অনিয়ম', 'ভ্যাট সংক্রান্ত অনিয়ম'), ('আবগারী শুল্ক সংক্রান্ত অনিয়ম', 'আবগারী শুল্ক সংক্রান্ত অনিয়ম'), ('অতিরিক্ত সুদ প্রদান', 'অতিরিক্ত সুদ প্রদান'), ('ঋণ সংশ্লিষ্ট অনিয়ম', 'ঋণ সংশ্লিষ্ট অনিয়ম'), ('তামাদি ঋণ', 'তামাদি ঋণ'), ('ভুয়া ঋণ', 'ভুয়া ঋণ'), ('মেয়াদোত্তীর্ণ অনাদায়ী ঋণ', 'মেয়াদোত্তীর্ণ অনাদায়ী ঋণ'), ('গৃহ নির্মাণ অগ্রিম (জমি ক্রয় সংক্রান্ত অনিয়ম)', 'গৃহ নির্মাণ অগ্রিম (জমি ক্রয় সংক্রান্ত অনিয়ম)'), ('লাঞ্চ সাবসিডি', 'লাঞ্চ সাবসিডি'), ('বিবিধ', 'বিবিধ')], default='আর্থিক বিধি অনুসরণ করা হয় নাই', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='suit_type',
            field=models.CharField(choices=[('সার্টিফিকেট মামলা', 'সার্টিফিকেট মামলা'), ('অর্থ ঋণ মামলা', 'অর্থ ঋণ মামলা'), ('ফৌজদারী মামলা', 'ফৌজদারী মামলা'), ('মানিস্যুট মামলা', 'মানিস্যুট মামলা'), ('অন্যান্য মামলা', 'অন্যান্য মামলা')], default='সার্টিফিকেট', max_length=100),
        ),
    ]
