# Generated by Django 3.0.7 on 2020-11-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_management', '0009_auto_20201101_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='issued_letter_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='issued_letter_no',
        ),
    ]
